package com.andrew.smartielts.dashboard.agent;

public enum DashboardCapability {
    USER_SELF_OVERVIEW,
    USER_SELF_RECENT_RECORDS,
    USER_SELF_PROGRESS_SUMMARY,
    USER_SELF_DELETED_SUMMARY,
    USER_SELF_MODULE_STATS,

    ADMIN_GLOBAL_OVERVIEW,
    ADMIN_USER_COUNT,
    ADMIN_AI_FAILURE_SUMMARY,
    ADMIN_MODULE_STATS,
    ADMIN_USER_RECORD_SUMMARY,
    ADMIN_RECENT_ISSUES,

    STRUCTURED_QUERY
}